name: Build gba-cores

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout & build the repo in buildroot
      run: |
        docker run \
        -v ${{ github.workspace }}:/root/workspace \
        techdevangelist/miyoomini-buildroot:latest /bin/bash -c \
        "cd /root/workspace && git submodule init && git submodule update && patch -p0 <  buildbot-tweaks.patch && cd libretro-super && ./libretro-buildbot-recipe.sh ../gba-cores && pwd && cd dist/unix && ls -lah ./"
    - name: Upload the build artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: gba-cores
        path: libretro-super/dist/unix/*
        if-no-files-found: error
        retention-days: 90
